name = "App-sdif"
script_files = [ "script/sdif", "script/cdif", "script/watchdiff" ]
badges = ['travis-ci.org', 'metacpan']
authority="cpan:UTASHIRO"
module_maker="ModuleBuildTiny"
[unsupported]
os = [
    "MSWin32",
]
